// generated by gpt-5-mini
export interface GetHistoryResponse {
  ok: boolean;
  pagesize: number;
  messages: Message[];
  parentmessages: Message[];
}

export interface Message {
  id: number;
  bubble_id: number;
  user_id: number;
  message: string;
  resource_id: number | null;
  clickcount: number;
  likecount: number;
  dislikecount: number;
  viewcount: number;
  version: number;
  user_edited_version: number;
  user_edited_at: string | null;
  created_at: string;
  updated_at: string;
  livestream_id: number | null;
  videosession_id: number | null;
  systemmessageparts: unknown | null;
  uuid: string;
  task_id: number | null;
  parentmessage_id: number | null;
  firstchildmessage_id: number | null;
  lastchildmessage_id: number | null;
  poll_id: number | null;
  systemevent: unknown | null;
  reactionsummary: ReactionSummary[];
  lang: string | null;
  videosession: unknown | null;
  // to satisfy eslint when using json imports
  mentions: (Mention | any)[]; // sometimes empty
  messagemedia: Media[]; // sometimes empty
  messagetrans: unknown[]; // translation objects not present in sample
  resource: Resource | null;
  task: unknown | null;
  user: User;
  poll: unknown | null;
}

export interface ReactionSummary {
  message_id: number;
  emoji: string;
  emoji_base: string;
  reactiontype_id: number;
  count: number;
  users: number[]; // sample shows numeric user ids or empty array
}

export interface Mention {
  id: number;
  firstname: string;
  lastname: string;
  profilepic?: boolean;
  deactivated_at?: string | null;
  created_at?: string;
  updated_at?: string;
  profilepicurl?: string;
  profilepicpath?: string;
  fullname?: string;
}

export interface Media {
  id: number;
  message_id: number;
  url: string;
  thumbnail: string;
  width: number;
  height: number;
  filesize: number;
  duration: number | null;
  created_at: string;
  updated_at: string;
  title: string;
  external: boolean;
  uuid: string;
  mediatype: "PHOTO" | "VIDEO" | string;
  urlmimetype: string | null;
  thumbnailmimetype: string | null;
  path: string;
  thumbnailpath: string | null;
}

export interface Resource {
  id: number;
  providername: string;
  providerurl: string;
  snippet: string | null;
  url: string;
  thumbnailurl: string | null;
  thumbnailheight: number | null;
  thumbnailwidth: number | null;
  imageurl: string | null;
  videourl: string | null;
  videoheight: number;
  videowidth: number;
  title: string;
  externalid: string | null;
  meta: unknown | null;
  clickcount: number;
  likecount: number;
  dislikecount: number;
  viewcount: number;
  embedly: boolean;
  publisheddate: string | null;
  created_at: string;
  updated_at: string;
  serviceprovider: string | null;
  resourcetype: string | null;
}

export interface User {
  id: number;
  firstname: string;
  lastname: string;
  username: string | null;
  locale: string | null;
  lastseen: string;
  profilepic: boolean;
  status: number;
  created_at: string;
  updated_at: string;
  deactivated_at: string | null;
  email_verified_at: string | null;
  phone_verified_at: string | null;
  isverified: boolean;
  dropinorder: number;
  maxstreams: number;
  autotranslate: boolean;
  isonline: boolean;
  lastpresencetime: string | null;
  acceptedtos: string | null;
  sentwelcomemsg: string | null;
  role: string;
  mute: boolean;
  muteuntil: string | null;
  isbot: number;
  fullname: string;
  hasactivity: boolean;
  inactive: boolean;
  language: string;
  permissions: Permissions;
  profilepicpath: string | null;
  profilepicurl: string | null;
}

export interface Permissions {
  change_name: string | boolean;
  change_email: string | boolean;
  change_phone: string | boolean;
  remove_user: string | boolean;
  change_title: string | boolean;
  change_pronouns: string | boolean;
  change_own_name: boolean;
  change_own_email: boolean;
  change_own_phone: boolean;
  change_own_title: boolean;
  change_own_pronouns: boolean;
}
